### ISSUE TITLE
Any updates on "cursor shifting to beginning of the line" issue fix?

### ISSUE THREAD

**Issue by mohitWrangler** [Penguinlay/notion-inline-latex#1]

**Comment by Penguinlay** [comment]
Not yet. I will look into it more this weekend! If you or anyone knows how to fix, feel free to make pull request regarding this issue!

**Comment by howyay** [comment]
> _No description provided._

You could try what I did in #2, it should ease the problem when typing though not fully solving it

**Comment by Penguinlay** [comment]
obsolete
