### ISSUE TITLE
Router ClientCrash when navigating between pages

### ISSUE THREAD

**Issue by howyay** [Penguinlay/notion-inline-latex#3]
Happens whenever I go thru different pages

[error] Router ClientCrash
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Oo (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1304396)
    at Ss (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1322879)
    at t.unstable_runWithPriority (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:60014)
    at pa (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1271552)
    at Ls (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1320617)
    at hs (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1309356)
    at https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1271824
    at t.unstable_runWithPriority (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:60014)
    at pa (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1271552)
    at _a (https://www.notion.so/vendors~main-671e15f8ce06b94dbee9.js:1:1271769)
```

**Comment by zibo-ye** [comment]
Same crash here, but happens only when creating a new page:
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Oo (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1304396)
    at Ss (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1322879)
    at t.unstable_runWithPriority (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:60014)
    at pa (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271552)
    at Ls (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1320617)
    at hs (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1309356)
    at https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271824
    at t.unstable_runWithPriority (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:60014)
    at pa (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271552)
    at _a (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271769)
```

**Comment by howyay** [comment]
Not sure if this is fixable... Problem seems to be that KaTeX auto-render made some change to the node that Notion will try to delete a node thats not there

**Comment by howyay** [comment]
> Same crash here, but happens only when creating a new page:
> 
> ```
> DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
>     at Oo (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1304396)
>     at Ss (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1322879)
>     at t.unstable_runWithPriority (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:60014)
>     at pa (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271552)
>     at Ls (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1320617)
>     at hs (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1309356)
>     at https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271824
>     at t.unstable_runWithPriority (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:60014)
>     at pa (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271552)
>     at _a (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271769)
> ```

I think I have found to way to avoid this, but it requires a modified auto-render.js
You just need to add a check for (childNode.textContent.includes("\$")) before replaceChild(),
so non inline math text doesn't get replaced and break stuff

Here's the commit where I modified auto-render.js
[f633cdd963413765f5c9f9c6eabcf56dac52ba1a](https://github.com/howyay/js-hosting/commit/f633cdd963413765f5c9f9c6eabcf56dac52ba1a)

or you can use jsDelivr to use the script directly from my repo
https://cdn.jsdelivr.net/gh/howyay/js-hosting@f633cdd963413765f5c9f9c6eabcf56dac52ba1a/katex/contrib/auto-render.min.js

**Comment by zibo-ye** [comment]
> > Same crash here, but happens only when creating a new page:
> > ```
> > DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> >     at Oo (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1304396)
> >     at Ss (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1322879)
> >     at t.unstable_runWithPriority (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:60014)
> >     at pa (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271552)
> >     at Ls (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1320617)
> >     at hs (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1309356)
> >     at https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271824
> >     at t.unstable_runWithPriority (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:60014)
> >     at pa (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271552)
> >     at _a (https://www.notion.so/vendors~main-eb4e2c6ecbccb79d40d2.js:1:1271769)
> > ```
> 
> I think I have found to way to avoid this, but it requires a modified auto-render.js
> You just need to add a check for (childNode.textContent.includes("$")) before replaceChild(),
> so non inline math text doesn't get replaced and break stuff
> 
> Here's the commit where I modified auto-render.js
> [f633cdd963413765f5c9f9c6eabcf56dac52ba1a](https://github.com/howyay/js-hosting/commit/f633cdd963413765f5c9f9c6eabcf56dac52ba1a)
> 
> or you can use jsDelivr to use the script directly from my repo
> https://cdn.jsdelivr.net/gh/howyay/js-hosting@f633cdd963413765f5c9f9c6eabcf56dac52ba1a/katex/contrib/auto-render.min.js

Thx a lot, it worked!

```javascript
// ==UserScript==
// @name            Notion Inline LaTeX
// @namespace       https://github.com/Penguinlay/notion-inline-latex
// @match           https://www.notion.so/*
// @version         0.5
// @description     User Script for Inline LaTeX Rendering in notion.so
// @require         https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js
// @require         https://cdn.jsdelivr.net/gh/howyay/js-hosting@f633cdd963413765f5c9f9c6eabcf56dac52ba1a/katex/contrib/auto-render.min.js
// @grant           GM_addStyle
// ==/UserScript==

// Note:
// Script does not change the content.
// It merely changes the display after the contents are loaded.
// Need at least one math block present on the page for the script to work properly.
// Small value for startUpWaitTime and keyUpWaitTime can make the script load improperly.
// Add delimiters as desired though delimiters other than default one have not been tested yet.

// Acknowledgement
// This script is inspired by the project by Evert Heylen.
// https://github.com/evertheylen/notion-inline-math

// right-padding for inline math mode
GM_addStyle(`
.katex {
    padding-right: 0 !important;
}
`);

// declare/init vars
let timer; // timer identifier
let startUpWaitTime = 500; // ms after startup (adjust as needed)
let mouseUpWaitTime = 5000; // ms after startup (adjust as needed)
let keyUpWaitTime = 500; // ms after keyup   (adjust as needed)

// render inline LaTeX
function renderInlineLaTeX() {
    try{
        renderMathInElement(document.body, {
            delimiters: [
                // LaTeX delimiters (uncomment/add as needed)
                // { left: "$$" , right: "$$" , display: true  },
                // { left: "\\[", right: "\\]", display: true  },
                // { left: "\\(", right: "\\)", display: false },
                { left: "$", right: "$", display: false }
            ]
        });
        console.log("Inline LaTeX is rendered.");
    }
    catch(e)
    {
        console.error(e);
    }
}

// on startup...
console.log("Rendering inline LaTeX on startup...");
clearTimeout(timer);
timer = setTimeout(renderInlineLaTeX, startUpWaitTime);

// on keyup...
document.addEventListener("keyup", () => {
  console.log("Rendering inline LaTeX on keyup...");
  clearTimeout(timer);
  timer = setTimeout(renderInlineLaTeX, keyUpWaitTime);
});

// on mouse...
document.addEventListener("mouseup", () => {
  console.log("Rendering inline LaTeX on mouseup...");
  clearTimeout(timer);
  timer = setTimeout(renderInlineLaTeX, mouseUpWaitTime);
});
```

**Comment by Penguinlay** [comment]
Hi, sorry for afk. I've been dealing with personal health lately. I will look into this more this weekend. Thanks for keeping up with the issue and replies!
