### ISSUE TITLE
Future Development?

### ISSUE THREAD

**Issue by Penguinlay** [Penguinlay/notion-inline-latex#7]
Since inline LaTeX has been [on Notion officially](https://www.notion.so/Math-equations-b4e9e4e03677413481a4910e8bd328c1#ce0033e960964fb2b30d56d09e98c5ba) now as most of you might already know, I am wondering if you all would want to keep this project active or archived.

**Comment by yujie6** [comment]
Hello, I think there could be an option to add user macros, which can saves a lot of time. And it's easy to implement since there is an api. Plus using snnipets in inline-latex is also an awesome feature, just like the one in vscode. For example, when you type `@l`, you get `lambda`.

**Comment by Penguinlay** [comment]
For snippet, it is just a simple modification of the current script. For other features like macros, it will be more suitable to start a new project, I believe.

**Comment by Penguinlay** [comment]
obsolete
